// Generated by packages/ui/scripts/build-tokens.mjs from tokens.json. Do not edit by hand.

export type TokenType = "color" | "number" | "fontFamily" | "fontWeight" | "unknown"

export interface Token {
  /** CSS custom property name, e.g. `--sds-color-brand-800`. */
  cssVar: string
  /** Figma collection the token came from. */
  collection: "color_primitives" | "color" | "size" | "typography_primitives" | "typography"
  /** Path inside the collection, e.g. ["background", "brand", "default"]. */
  path: string[]
  type: TokenType
  description?: string
  /** CSS value in light mode (may reference another token via var()). */
  light: string
  /** CSS value in dark mode; only semantic colours have one. */
  dark?: string
  /** Fully resolved literal in light mode (hex, px number, family, …). */
  resolvedLight: string
  /** Fully resolved literal in dark mode. */
  resolvedDark?: string
}

export const tokens: readonly Token[] = [
  {
    "cssVar": "--sds-color-brand-100",
    "collection": "color_primitives",
    "path": [
      "brand",
      "100"
    ],
    "type": "color",
    "light": "#f5f5f5",
    "resolvedLight": "#f5f5f5"
  },
  {
    "cssVar": "--sds-color-brand-200",
    "collection": "color_primitives",
    "path": [
      "brand",
      "200"
    ],
    "type": "color",
    "light": "#e6e6e6",
    "resolvedLight": "#e6e6e6"
  },
  {
    "cssVar": "--sds-color-brand-300",
    "collection": "color_primitives",
    "path": [
      "brand",
      "300"
    ],
    "type": "color",
    "light": "#d9d9d9",
    "resolvedLight": "#d9d9d9"
  },
  {
    "cssVar": "--sds-color-brand-400",
    "collection": "color_primitives",
    "path": [
      "brand",
      "400"
    ],
    "type": "color",
    "light": "#b3b3b3",
    "resolvedLight": "#b3b3b3"
  },
  {
    "cssVar": "--sds-color-brand-500",
    "collection": "color_primitives",
    "path": [
      "brand",
      "500"
    ],
    "type": "color",
    "light": "#757575",
    "resolvedLight": "#757575"
  },
  {
    "cssVar": "--sds-color-brand-600",
    "collection": "color_primitives",
    "path": [
      "brand",
      "600"
    ],
    "type": "color",
    "light": "#444444",
    "resolvedLight": "#444444"
  },
  {
    "cssVar": "--sds-color-brand-700",
    "collection": "color_primitives",
    "path": [
      "brand",
      "700"
    ],
    "type": "color",
    "light": "#383838",
    "resolvedLight": "#383838"
  },
  {
    "cssVar": "--sds-color-brand-800",
    "collection": "color_primitives",
    "path": [
      "brand",
      "800"
    ],
    "type": "color",
    "light": "#2c2c2c",
    "resolvedLight": "#2c2c2c"
  },
  {
    "cssVar": "--sds-color-brand-900",
    "collection": "color_primitives",
    "path": [
      "brand",
      "900"
    ],
    "type": "color",
    "light": "#1e1e1e",
    "resolvedLight": "#1e1e1e"
  },
  {
    "cssVar": "--sds-color-brand-1000",
    "collection": "color_primitives",
    "path": [
      "brand",
      "1000"
    ],
    "type": "color",
    "light": "#111111",
    "resolvedLight": "#111111"
  },
  {
    "cssVar": "--sds-color-black-100",
    "collection": "color_primitives",
    "path": [
      "black",
      "100"
    ],
    "type": "color",
    "light": "#0c0c0d0d",
    "resolvedLight": "#0c0c0d0d"
  },
  {
    "cssVar": "--sds-color-black-200",
    "collection": "color_primitives",
    "path": [
      "black",
      "200"
    ],
    "type": "color",
    "light": "#0c0c0d1a",
    "resolvedLight": "#0c0c0d1a"
  },
  {
    "cssVar": "--sds-color-black-300",
    "collection": "color_primitives",
    "path": [
      "black",
      "300"
    ],
    "type": "color",
    "light": "#0c0c0d33",
    "resolvedLight": "#0c0c0d33"
  },
  {
    "cssVar": "--sds-color-black-400",
    "collection": "color_primitives",
    "path": [
      "black",
      "400"
    ],
    "type": "color",
    "light": "#0c0c0d66",
    "resolvedLight": "#0c0c0d66"
  },
  {
    "cssVar": "--sds-color-black-500",
    "collection": "color_primitives",
    "path": [
      "black",
      "500"
    ],
    "type": "color",
    "light": "#0c0c0db2",
    "resolvedLight": "#0c0c0db2"
  },
  {
    "cssVar": "--sds-color-black-600",
    "collection": "color_primitives",
    "path": [
      "black",
      "600"
    ],
    "type": "color",
    "light": "#0c0c0dcc",
    "resolvedLight": "#0c0c0dcc"
  },
  {
    "cssVar": "--sds-color-black-700",
    "collection": "color_primitives",
    "path": [
      "black",
      "700"
    ],
    "type": "color",
    "light": "#0c0c0dd9",
    "resolvedLight": "#0c0c0dd9"
  },
  {
    "cssVar": "--sds-color-black-800",
    "collection": "color_primitives",
    "path": [
      "black",
      "800"
    ],
    "type": "color",
    "light": "#0c0c0de5",
    "resolvedLight": "#0c0c0de5"
  },
  {
    "cssVar": "--sds-color-black-900",
    "collection": "color_primitives",
    "path": [
      "black",
      "900"
    ],
    "type": "color",
    "light": "#0c0c0df2",
    "resolvedLight": "#0c0c0df2"
  },
  {
    "cssVar": "--sds-color-black-1000",
    "collection": "color_primitives",
    "path": [
      "black",
      "1000"
    ],
    "type": "color",
    "light": "#0c0c0d",
    "resolvedLight": "#0c0c0d"
  },
  {
    "cssVar": "--sds-color-white-100",
    "collection": "color_primitives",
    "path": [
      "white",
      "100"
    ],
    "type": "color",
    "light": "#ffffff0d",
    "resolvedLight": "#ffffff0d"
  },
  {
    "cssVar": "--sds-color-white-200",
    "collection": "color_primitives",
    "path": [
      "white",
      "200"
    ],
    "type": "color",
    "light": "#ffffff1a",
    "resolvedLight": "#ffffff1a"
  },
  {
    "cssVar": "--sds-color-white-300",
    "collection": "color_primitives",
    "path": [
      "white",
      "300"
    ],
    "type": "color",
    "light": "#ffffff33",
    "resolvedLight": "#ffffff33"
  },
  {
    "cssVar": "--sds-color-white-400",
    "collection": "color_primitives",
    "path": [
      "white",
      "400"
    ],
    "type": "color",
    "light": "#ffffff66",
    "resolvedLight": "#ffffff66"
  },
  {
    "cssVar": "--sds-color-white-500",
    "collection": "color_primitives",
    "path": [
      "white",
      "500"
    ],
    "type": "color",
    "light": "#ffffffb2",
    "resolvedLight": "#ffffffb2"
  },
  {
    "cssVar": "--sds-color-white-600",
    "collection": "color_primitives",
    "path": [
      "white",
      "600"
    ],
    "type": "color",
    "light": "#ffffffcc",
    "resolvedLight": "#ffffffcc"
  },
  {
    "cssVar": "--sds-color-white-700",
    "collection": "color_primitives",
    "path": [
      "white",
      "700"
    ],
    "type": "color",
    "light": "#ffffffd9",
    "resolvedLight": "#ffffffd9"
  },
  {
    "cssVar": "--sds-color-white-800",
    "collection": "color_primitives",
    "path": [
      "white",
      "800"
    ],
    "type": "color",
    "light": "#ffffffe5",
    "resolvedLight": "#ffffffe5"
  },
  {
    "cssVar": "--sds-color-white-900",
    "collection": "color_primitives",
    "path": [
      "white",
      "900"
    ],
    "type": "color",
    "light": "#fffffff2",
    "resolvedLight": "#fffffff2"
  },
  {
    "cssVar": "--sds-color-white-1000",
    "collection": "color_primitives",
    "path": [
      "white",
      "1000"
    ],
    "type": "color",
    "light": "#ffffff",
    "resolvedLight": "#ffffff"
  },
  {
    "cssVar": "--sds-color-green-100",
    "collection": "color_primitives",
    "path": [
      "green",
      "100"
    ],
    "type": "color",
    "light": "#ebffee",
    "resolvedLight": "#ebffee"
  },
  {
    "cssVar": "--sds-color-green-200",
    "collection": "color_primitives",
    "path": [
      "green",
      "200"
    ],
    "type": "color",
    "light": "#cff7d3",
    "resolvedLight": "#cff7d3"
  },
  {
    "cssVar": "--sds-color-green-300",
    "collection": "color_primitives",
    "path": [
      "green",
      "300"
    ],
    "type": "color",
    "light": "#aff4c6",
    "resolvedLight": "#aff4c6"
  },
  {
    "cssVar": "--sds-color-green-400",
    "collection": "color_primitives",
    "path": [
      "green",
      "400"
    ],
    "type": "color",
    "light": "#85e0a3",
    "resolvedLight": "#85e0a3"
  },
  {
    "cssVar": "--sds-color-green-500",
    "collection": "color_primitives",
    "path": [
      "green",
      "500"
    ],
    "type": "color",
    "light": "#14ae5c",
    "resolvedLight": "#14ae5c"
  },
  {
    "cssVar": "--sds-color-green-600",
    "collection": "color_primitives",
    "path": [
      "green",
      "600"
    ],
    "type": "color",
    "light": "#009951",
    "resolvedLight": "#009951"
  },
  {
    "cssVar": "--sds-color-green-700",
    "collection": "color_primitives",
    "path": [
      "green",
      "700"
    ],
    "type": "color",
    "light": "#008043",
    "resolvedLight": "#008043"
  },
  {
    "cssVar": "--sds-color-green-800",
    "collection": "color_primitives",
    "path": [
      "green",
      "800"
    ],
    "type": "color",
    "light": "#02542d",
    "resolvedLight": "#02542d"
  },
  {
    "cssVar": "--sds-color-green-900",
    "collection": "color_primitives",
    "path": [
      "green",
      "900"
    ],
    "type": "color",
    "light": "#024023",
    "resolvedLight": "#024023"
  },
  {
    "cssVar": "--sds-color-green-1000",
    "collection": "color_primitives",
    "path": [
      "green",
      "1000"
    ],
    "type": "color",
    "light": "#062d1b",
    "resolvedLight": "#062d1b"
  },
  {
    "cssVar": "--sds-color-gray-100",
    "collection": "color_primitives",
    "path": [
      "gray",
      "100"
    ],
    "type": "color",
    "light": "#f5f5f5",
    "resolvedLight": "#f5f5f5"
  },
  {
    "cssVar": "--sds-color-gray-200",
    "collection": "color_primitives",
    "path": [
      "gray",
      "200"
    ],
    "type": "color",
    "light": "#e6e6e6",
    "resolvedLight": "#e6e6e6"
  },
  {
    "cssVar": "--sds-color-gray-300",
    "collection": "color_primitives",
    "path": [
      "gray",
      "300"
    ],
    "type": "color",
    "light": "#d9d9d9",
    "resolvedLight": "#d9d9d9"
  },
  {
    "cssVar": "--sds-color-gray-400",
    "collection": "color_primitives",
    "path": [
      "gray",
      "400"
    ],
    "type": "color",
    "light": "#b3b3b3",
    "resolvedLight": "#b3b3b3"
  },
  {
    "cssVar": "--sds-color-gray-500",
    "collection": "color_primitives",
    "path": [
      "gray",
      "500"
    ],
    "type": "color",
    "light": "#757575",
    "resolvedLight": "#757575"
  },
  {
    "cssVar": "--sds-color-gray-600",
    "collection": "color_primitives",
    "path": [
      "gray",
      "600"
    ],
    "type": "color",
    "light": "#444444",
    "resolvedLight": "#444444"
  },
  {
    "cssVar": "--sds-color-gray-700",
    "collection": "color_primitives",
    "path": [
      "gray",
      "700"
    ],
    "type": "color",
    "light": "#383838",
    "resolvedLight": "#383838"
  },
  {
    "cssVar": "--sds-color-gray-800",
    "collection": "color_primitives",
    "path": [
      "gray",
      "800"
    ],
    "type": "color",
    "light": "#2c2c2c",
    "resolvedLight": "#2c2c2c"
  },
  {
    "cssVar": "--sds-color-gray-900",
    "collection": "color_primitives",
    "path": [
      "gray",
      "900"
    ],
    "type": "color",
    "light": "#1e1e1e",
    "resolvedLight": "#1e1e1e"
  },
  {
    "cssVar": "--sds-color-gray-1000",
    "collection": "color_primitives",
    "path": [
      "gray",
      "1000"
    ],
    "type": "color",
    "light": "#111111",
    "resolvedLight": "#111111"
  },
  {
    "cssVar": "--sds-color-pink-100",
    "collection": "color_primitives",
    "path": [
      "pink",
      "100"
    ],
    "type": "color",
    "light": "#fcf1fd",
    "resolvedLight": "#fcf1fd"
  },
  {
    "cssVar": "--sds-color-pink-200",
    "collection": "color_primitives",
    "path": [
      "pink",
      "200"
    ],
    "type": "color",
    "light": "#fae1fa",
    "resolvedLight": "#fae1fa"
  },
  {
    "cssVar": "--sds-color-pink-300",
    "collection": "color_primitives",
    "path": [
      "pink",
      "300"
    ],
    "type": "color",
    "light": "#f5c0ef",
    "resolvedLight": "#f5c0ef"
  },
  {
    "cssVar": "--sds-color-pink-400",
    "collection": "color_primitives",
    "path": [
      "pink",
      "400"
    ],
    "type": "color",
    "light": "#f19edc",
    "resolvedLight": "#f19edc"
  },
  {
    "cssVar": "--sds-color-pink-500",
    "collection": "color_primitives",
    "path": [
      "pink",
      "500"
    ],
    "type": "color",
    "light": "#ea3fb8",
    "resolvedLight": "#ea3fb8"
  },
  {
    "cssVar": "--sds-color-pink-600",
    "collection": "color_primitives",
    "path": [
      "pink",
      "600"
    ],
    "type": "color",
    "light": "#d732a8",
    "resolvedLight": "#d732a8"
  },
  {
    "cssVar": "--sds-color-pink-700",
    "collection": "color_primitives",
    "path": [
      "pink",
      "700"
    ],
    "type": "color",
    "light": "#ba2a92",
    "resolvedLight": "#ba2a92"
  },
  {
    "cssVar": "--sds-color-pink-800",
    "collection": "color_primitives",
    "path": [
      "pink",
      "800"
    ],
    "type": "color",
    "light": "#8a226f",
    "resolvedLight": "#8a226f"
  },
  {
    "cssVar": "--sds-color-pink-900",
    "collection": "color_primitives",
    "path": [
      "pink",
      "900"
    ],
    "type": "color",
    "light": "#57184a",
    "resolvedLight": "#57184a"
  },
  {
    "cssVar": "--sds-color-pink-1000",
    "collection": "color_primitives",
    "path": [
      "pink",
      "1000"
    ],
    "type": "color",
    "light": "#3f1536",
    "resolvedLight": "#3f1536"
  },
  {
    "cssVar": "--sds-color-red-100",
    "collection": "color_primitives",
    "path": [
      "red",
      "100"
    ],
    "type": "color",
    "light": "#fee9e7",
    "resolvedLight": "#fee9e7"
  },
  {
    "cssVar": "--sds-color-red-200",
    "collection": "color_primitives",
    "path": [
      "red",
      "200"
    ],
    "type": "color",
    "light": "#fdd3d0",
    "resolvedLight": "#fdd3d0"
  },
  {
    "cssVar": "--sds-color-red-300",
    "collection": "color_primitives",
    "path": [
      "red",
      "300"
    ],
    "type": "color",
    "light": "#fcb3ad",
    "resolvedLight": "#fcb3ad"
  },
  {
    "cssVar": "--sds-color-red-400",
    "collection": "color_primitives",
    "path": [
      "red",
      "400"
    ],
    "type": "color",
    "light": "#f4776a",
    "resolvedLight": "#f4776a"
  },
  {
    "cssVar": "--sds-color-red-500",
    "collection": "color_primitives",
    "path": [
      "red",
      "500"
    ],
    "type": "color",
    "light": "#ec221f",
    "resolvedLight": "#ec221f"
  },
  {
    "cssVar": "--sds-color-red-600",
    "collection": "color_primitives",
    "path": [
      "red",
      "600"
    ],
    "type": "color",
    "light": "#c00f0c",
    "resolvedLight": "#c00f0c"
  },
  {
    "cssVar": "--sds-color-red-700",
    "collection": "color_primitives",
    "path": [
      "red",
      "700"
    ],
    "type": "color",
    "light": "#900b09",
    "resolvedLight": "#900b09"
  },
  {
    "cssVar": "--sds-color-red-800",
    "collection": "color_primitives",
    "path": [
      "red",
      "800"
    ],
    "type": "color",
    "light": "#690807",
    "resolvedLight": "#690807"
  },
  {
    "cssVar": "--sds-color-red-900",
    "collection": "color_primitives",
    "path": [
      "red",
      "900"
    ],
    "type": "color",
    "light": "#4d0b0a",
    "resolvedLight": "#4d0b0a"
  },
  {
    "cssVar": "--sds-color-red-1000",
    "collection": "color_primitives",
    "path": [
      "red",
      "1000"
    ],
    "type": "color",
    "light": "#300603",
    "resolvedLight": "#300603"
  },
  {
    "cssVar": "--sds-color-slate-100",
    "collection": "color_primitives",
    "path": [
      "slate",
      "100"
    ],
    "type": "color",
    "light": "#f3f3f3",
    "resolvedLight": "#f3f3f3"
  },
  {
    "cssVar": "--sds-color-slate-200",
    "collection": "color_primitives",
    "path": [
      "slate",
      "200"
    ],
    "type": "color",
    "light": "#e3e3e3",
    "resolvedLight": "#e3e3e3"
  },
  {
    "cssVar": "--sds-color-slate-300",
    "collection": "color_primitives",
    "path": [
      "slate",
      "300"
    ],
    "type": "color",
    "light": "#cdcdcd",
    "resolvedLight": "#cdcdcd"
  },
  {
    "cssVar": "--sds-color-slate-400",
    "collection": "color_primitives",
    "path": [
      "slate",
      "400"
    ],
    "type": "color",
    "light": "#b2b2b2",
    "resolvedLight": "#b2b2b2"
  },
  {
    "cssVar": "--sds-color-slate-500",
    "collection": "color_primitives",
    "path": [
      "slate",
      "500"
    ],
    "type": "color",
    "light": "#949494",
    "resolvedLight": "#949494"
  },
  {
    "cssVar": "--sds-color-slate-600",
    "collection": "color_primitives",
    "path": [
      "slate",
      "600"
    ],
    "type": "color",
    "light": "#767676",
    "resolvedLight": "#767676"
  },
  {
    "cssVar": "--sds-color-slate-700",
    "collection": "color_primitives",
    "path": [
      "slate",
      "700"
    ],
    "type": "color",
    "light": "#5a5a5a",
    "resolvedLight": "#5a5a5a"
  },
  {
    "cssVar": "--sds-color-slate-800",
    "collection": "color_primitives",
    "path": [
      "slate",
      "800"
    ],
    "type": "color",
    "light": "#434343",
    "resolvedLight": "#434343"
  },
  {
    "cssVar": "--sds-color-slate-900",
    "collection": "color_primitives",
    "path": [
      "slate",
      "900"
    ],
    "type": "color",
    "light": "#303030",
    "resolvedLight": "#303030"
  },
  {
    "cssVar": "--sds-color-slate-1000",
    "collection": "color_primitives",
    "path": [
      "slate",
      "1000"
    ],
    "type": "color",
    "light": "#242424",
    "resolvedLight": "#242424"
  },
  {
    "cssVar": "--sds-color-yellow-100",
    "collection": "color_primitives",
    "path": [
      "yellow",
      "100"
    ],
    "type": "color",
    "light": "#fffbeb",
    "resolvedLight": "#fffbeb"
  },
  {
    "cssVar": "--sds-color-yellow-200",
    "collection": "color_primitives",
    "path": [
      "yellow",
      "200"
    ],
    "type": "color",
    "light": "#fff1c2",
    "resolvedLight": "#fff1c2"
  },
  {
    "cssVar": "--sds-color-yellow-300",
    "collection": "color_primitives",
    "path": [
      "yellow",
      "300"
    ],
    "type": "color",
    "light": "#ffe8a3",
    "resolvedLight": "#ffe8a3"
  },
  {
    "cssVar": "--sds-color-yellow-400",
    "collection": "color_primitives",
    "path": [
      "yellow",
      "400"
    ],
    "type": "color",
    "light": "#e8b931",
    "resolvedLight": "#e8b931"
  },
  {
    "cssVar": "--sds-color-yellow-500",
    "collection": "color_primitives",
    "path": [
      "yellow",
      "500"
    ],
    "type": "color",
    "light": "#e5a000",
    "resolvedLight": "#e5a000"
  },
  {
    "cssVar": "--sds-color-yellow-600",
    "collection": "color_primitives",
    "path": [
      "yellow",
      "600"
    ],
    "type": "color",
    "light": "#bf6a02",
    "resolvedLight": "#bf6a02"
  },
  {
    "cssVar": "--sds-color-yellow-700",
    "collection": "color_primitives",
    "path": [
      "yellow",
      "700"
    ],
    "type": "color",
    "light": "#975102",
    "resolvedLight": "#975102"
  },
  {
    "cssVar": "--sds-color-yellow-800",
    "collection": "color_primitives",
    "path": [
      "yellow",
      "800"
    ],
    "type": "color",
    "light": "#682d03",
    "resolvedLight": "#682d03"
  },
  {
    "cssVar": "--sds-color-yellow-900",
    "collection": "color_primitives",
    "path": [
      "yellow",
      "900"
    ],
    "type": "color",
    "light": "#522504",
    "resolvedLight": "#522504"
  },
  {
    "cssVar": "--sds-color-yellow-1000",
    "collection": "color_primitives",
    "path": [
      "yellow",
      "1000"
    ],
    "type": "color",
    "light": "#401b01",
    "resolvedLight": "#401b01"
  },
  {
    "cssVar": "--sds-color-background-default-default",
    "collection": "color",
    "path": [
      "background",
      "default",
      "default"
    ],
    "type": "color",
    "description": "Bg/Default/Default",
    "light": "var(--sds-color-white-1000)",
    "dark": "var(--sds-color-gray-900)",
    "resolvedLight": "#ffffff",
    "resolvedDark": "#1e1e1e"
  },
  {
    "cssVar": "--sds-color-background-default-default-hover",
    "collection": "color",
    "path": [
      "background",
      "default",
      "default-hover"
    ],
    "type": "color",
    "description": "Bg/Default/Default Hover",
    "light": "var(--sds-color-gray-100)",
    "dark": "var(--sds-color-gray-700)",
    "resolvedLight": "#f5f5f5",
    "resolvedDark": "#383838"
  },
  {
    "cssVar": "--sds-color-background-default-secondary",
    "collection": "color",
    "path": [
      "background",
      "default",
      "secondary"
    ],
    "type": "color",
    "description": "Bg/Default/Secondary",
    "light": "var(--sds-color-gray-100)",
    "dark": "var(--sds-color-gray-800)",
    "resolvedLight": "#f5f5f5",
    "resolvedDark": "#2c2c2c"
  },
  {
    "cssVar": "--sds-color-background-default-secondary-hover",
    "collection": "color",
    "path": [
      "background",
      "default",
      "secondary-hover"
    ],
    "type": "color",
    "description": "Bg/Default/Secondary Hover",
    "light": "var(--sds-color-gray-200)",
    "dark": "var(--sds-color-gray-900)",
    "resolvedLight": "#e6e6e6",
    "resolvedDark": "#1e1e1e"
  },
  {
    "cssVar": "--sds-color-background-default-tertiary",
    "collection": "color",
    "path": [
      "background",
      "default",
      "tertiary"
    ],
    "type": "color",
    "description": "Bg/Default/Tertiary",
    "light": "var(--sds-color-gray-300)",
    "dark": "var(--sds-color-gray-600)",
    "resolvedLight": "#d9d9d9",
    "resolvedDark": "#444444"
  },
  {
    "cssVar": "--sds-color-background-default-tertiary-hover",
    "collection": "color",
    "path": [
      "background",
      "default",
      "tertiary-hover"
    ],
    "type": "color",
    "description": "Bg/Default/Tertiary Hover",
    "light": "var(--sds-color-gray-400)",
    "dark": "var(--sds-color-gray-700)",
    "resolvedLight": "#b3b3b3",
    "resolvedDark": "#383838"
  },
  {
    "cssVar": "--sds-color-background-neutral-default",
    "collection": "color",
    "path": [
      "background",
      "neutral",
      "default"
    ],
    "type": "color",
    "description": "Bg/Neutral/Default",
    "light": "var(--sds-color-slate-700)",
    "dark": "var(--sds-color-slate-400)",
    "resolvedLight": "#5a5a5a",
    "resolvedDark": "#b2b2b2"
  },
  {
    "cssVar": "--sds-color-background-neutral-hover",
    "collection": "color",
    "path": [
      "background",
      "neutral",
      "hover"
    ],
    "type": "color",
    "description": "Bg/Neutral/Hover",
    "light": "var(--sds-color-slate-800)",
    "dark": "var(--sds-color-slate-500)",
    "resolvedLight": "#434343",
    "resolvedDark": "#949494"
  },
  {
    "cssVar": "--sds-color-background-neutral-secondary",
    "collection": "color",
    "path": [
      "background",
      "neutral",
      "secondary"
    ],
    "type": "color",
    "description": "Bg/Neutral/Secondary",
    "light": "var(--sds-color-slate-300)",
    "dark": "var(--sds-color-slate-900)",
    "resolvedLight": "#cdcdcd",
    "resolvedDark": "#303030"
  },
  {
    "cssVar": "--sds-color-background-neutral-secondary-hover",
    "collection": "color",
    "path": [
      "background",
      "neutral",
      "secondary-hover"
    ],
    "type": "color",
    "description": "Bg/Neutral/Secondary Hover",
    "light": "var(--sds-color-slate-400)",
    "dark": "var(--sds-color-slate-1000)",
    "resolvedLight": "#b2b2b2",
    "resolvedDark": "#242424"
  },
  {
    "cssVar": "--sds-color-background-neutral-tertiary",
    "collection": "color",
    "path": [
      "background",
      "neutral",
      "tertiary"
    ],
    "type": "color",
    "description": "Bg/Neutral/Tertiary",
    "light": "var(--sds-color-slate-200)",
    "dark": "var(--sds-color-slate-900)",
    "resolvedLight": "#e3e3e3",
    "resolvedDark": "#303030"
  },
  {
    "cssVar": "--sds-color-background-neutral-tertiary-hover",
    "collection": "color",
    "path": [
      "background",
      "neutral",
      "tertiary-hover"
    ],
    "type": "color",
    "description": "Bg/Neutral/Tertiary Hover",
    "light": "var(--sds-color-slate-300)",
    "dark": "var(--sds-color-slate-1000)",
    "resolvedLight": "#cdcdcd",
    "resolvedDark": "#242424"
  },
  {
    "cssVar": "--sds-color-background-brand-default",
    "collection": "color",
    "path": [
      "background",
      "brand",
      "default"
    ],
    "type": "color",
    "description": "Bg/Brand/Default",
    "light": "var(--sds-color-brand-800)",
    "dark": "var(--sds-color-brand-100)",
    "resolvedLight": "#2c2c2c",
    "resolvedDark": "#f5f5f5"
  },
  {
    "cssVar": "--sds-color-background-brand-hover",
    "collection": "color",
    "path": [
      "background",
      "brand",
      "hover"
    ],
    "type": "color",
    "description": "Bg/Brand/Hover",
    "light": "var(--sds-color-brand-900)",
    "dark": "var(--sds-color-brand-300)",
    "resolvedLight": "#1e1e1e",
    "resolvedDark": "#d9d9d9"
  },
  {
    "cssVar": "--sds-color-background-brand-secondary",
    "collection": "color",
    "path": [
      "background",
      "brand",
      "secondary"
    ],
    "type": "color",
    "description": "Bg/Brand/Secondary",
    "light": "var(--sds-color-brand-200)",
    "dark": "var(--sds-color-brand-600)",
    "resolvedLight": "#e6e6e6",
    "resolvedDark": "#444444"
  },
  {
    "cssVar": "--sds-color-background-brand-secondary-hover",
    "collection": "color",
    "path": [
      "background",
      "brand",
      "secondary-hover"
    ],
    "type": "color",
    "description": "Bg/Brand/Secondary Hover",
    "light": "var(--sds-color-brand-300)",
    "dark": "var(--sds-color-brand-500)",
    "resolvedLight": "#d9d9d9",
    "resolvedDark": "#757575"
  },
  {
    "cssVar": "--sds-color-background-brand-tertiary",
    "collection": "color",
    "path": [
      "background",
      "brand",
      "tertiary"
    ],
    "type": "color",
    "description": "Bg/Brand/Tertiary",
    "light": "var(--sds-color-brand-100)",
    "dark": "var(--sds-color-brand-600)",
    "resolvedLight": "#f5f5f5",
    "resolvedDark": "#444444"
  },
  {
    "cssVar": "--sds-color-background-brand-tertiary-hover",
    "collection": "color",
    "path": [
      "background",
      "brand",
      "tertiary-hover"
    ],
    "type": "color",
    "description": "Bg/Brand/Tertiary Hover",
    "light": "var(--sds-color-brand-200)",
    "dark": "var(--sds-color-brand-800)",
    "resolvedLight": "#e6e6e6",
    "resolvedDark": "#2c2c2c"
  },
  {
    "cssVar": "--sds-color-background-positive-default",
    "collection": "color",
    "path": [
      "background",
      "positive",
      "default"
    ],
    "type": "color",
    "description": "Bg/Positive/Default",
    "light": "var(--sds-color-green-500)",
    "dark": "var(--sds-color-green-700)",
    "resolvedLight": "#14ae5c",
    "resolvedDark": "#008043"
  },
  {
    "cssVar": "--sds-color-background-positive-hover",
    "collection": "color",
    "path": [
      "background",
      "positive",
      "hover"
    ],
    "type": "color",
    "description": "Bg/Positive/Hover",
    "light": "var(--sds-color-green-600)",
    "dark": "var(--sds-color-green-800)",
    "resolvedLight": "#009951",
    "resolvedDark": "#02542d"
  },
  {
    "cssVar": "--sds-color-background-positive-secondary",
    "collection": "color",
    "path": [
      "background",
      "positive",
      "secondary"
    ],
    "type": "color",
    "description": "Bg/Positive/Secondary",
    "light": "var(--sds-color-green-200)",
    "dark": "var(--sds-color-green-800)",
    "resolvedLight": "#cff7d3",
    "resolvedDark": "#02542d"
  },
  {
    "cssVar": "--sds-color-background-positive-secondary-hover",
    "collection": "color",
    "path": [
      "background",
      "positive",
      "secondary-hover"
    ],
    "type": "color",
    "description": "Bg/Positive/Secondary Hover",
    "light": "var(--sds-color-green-300)",
    "dark": "var(--sds-color-green-900)",
    "resolvedLight": "#aff4c6",
    "resolvedDark": "#024023"
  },
  {
    "cssVar": "--sds-color-background-positive-tertiary",
    "collection": "color",
    "path": [
      "background",
      "positive",
      "tertiary"
    ],
    "type": "color",
    "description": "Bg/Positive/Tertiary",
    "light": "var(--sds-color-green-100)",
    "dark": "var(--sds-color-green-900)",
    "resolvedLight": "#ebffee",
    "resolvedDark": "#024023"
  },
  {
    "cssVar": "--sds-color-background-positive-tertiary-hover",
    "collection": "color",
    "path": [
      "background",
      "positive",
      "tertiary-hover"
    ],
    "type": "color",
    "description": "Bg/Positive/Tertiary Hover",
    "light": "var(--sds-color-green-200)",
    "dark": "var(--sds-color-green-1000)",
    "resolvedLight": "#cff7d3",
    "resolvedDark": "#062d1b"
  },
  {
    "cssVar": "--sds-color-background-warning-default",
    "collection": "color",
    "path": [
      "background",
      "warning",
      "default"
    ],
    "type": "color",
    "description": "Bg/Warning/Default",
    "light": "var(--sds-color-yellow-400)",
    "dark": "var(--sds-color-yellow-400)",
    "resolvedLight": "#e8b931",
    "resolvedDark": "#e8b931"
  },
  {
    "cssVar": "--sds-color-background-warning-hover",
    "collection": "color",
    "path": [
      "background",
      "warning",
      "hover"
    ],
    "type": "color",
    "description": "Bg/Warning/Hover",
    "light": "var(--sds-color-yellow-500)",
    "dark": "var(--sds-color-yellow-500)",
    "resolvedLight": "#e5a000",
    "resolvedDark": "#e5a000"
  },
  {
    "cssVar": "--sds-color-background-warning-secondary",
    "collection": "color",
    "path": [
      "background",
      "warning",
      "secondary"
    ],
    "type": "color",
    "description": "Bg/Warning/Secondary",
    "light": "var(--sds-color-yellow-200)",
    "dark": "var(--sds-color-yellow-800)",
    "resolvedLight": "#fff1c2",
    "resolvedDark": "#682d03"
  },
  {
    "cssVar": "--sds-color-background-warning-secondary-hover",
    "collection": "color",
    "path": [
      "background",
      "warning",
      "secondary-hover"
    ],
    "type": "color",
    "description": "Bg/Warning/Secondary Hover",
    "light": "var(--sds-color-yellow-300)",
    "dark": "var(--sds-color-yellow-900)",
    "resolvedLight": "#ffe8a3",
    "resolvedDark": "#522504"
  },
  {
    "cssVar": "--sds-color-background-warning-tertiary",
    "collection": "color",
    "path": [
      "background",
      "warning",
      "tertiary"
    ],
    "type": "color",
    "description": "Bg/Warning/Tertiary",
    "light": "var(--sds-color-yellow-100)",
    "dark": "var(--sds-color-yellow-900)",
    "resolvedLight": "#fffbeb",
    "resolvedDark": "#522504"
  },
  {
    "cssVar": "--sds-color-background-warning-tertiary-hover",
    "collection": "color",
    "path": [
      "background",
      "warning",
      "tertiary-hover"
    ],
    "type": "color",
    "description": "Bg/Warning/Tertiary Hover",
    "light": "var(--sds-color-yellow-200)",
    "dark": "var(--sds-color-yellow-1000)",
    "resolvedLight": "#fff1c2",
    "resolvedDark": "#401b01"
  },
  {
    "cssVar": "--sds-color-background-danger-default",
    "collection": "color",
    "path": [
      "background",
      "danger",
      "default"
    ],
    "type": "color",
    "description": "Bg/Danger/Default",
    "light": "var(--sds-color-red-500)",
    "dark": "var(--sds-color-red-600)",
    "resolvedLight": "#ec221f",
    "resolvedDark": "#c00f0c"
  },
  {
    "cssVar": "--sds-color-background-danger-hover",
    "collection": "color",
    "path": [
      "background",
      "danger",
      "hover"
    ],
    "type": "color",
    "description": "Bg/Danger/Hover",
    "light": "var(--sds-color-red-600)",
    "dark": "var(--sds-color-red-700)",
    "resolvedLight": "#c00f0c",
    "resolvedDark": "#900b09"
  },
  {
    "cssVar": "--sds-color-background-danger-secondary",
    "collection": "color",
    "path": [
      "background",
      "danger",
      "secondary"
    ],
    "type": "color",
    "description": "Bg/Danger/Secondary",
    "light": "var(--sds-color-red-200)",
    "dark": "var(--sds-color-red-800)",
    "resolvedLight": "#fdd3d0",
    "resolvedDark": "#690807"
  },
  {
    "cssVar": "--sds-color-background-danger-secondary-hover",
    "collection": "color",
    "path": [
      "background",
      "danger",
      "secondary-hover"
    ],
    "type": "color",
    "description": "Bg/Danger/Secondary Hover",
    "light": "var(--sds-color-red-300)",
    "dark": "var(--sds-color-red-900)",
    "resolvedLight": "#fcb3ad",
    "resolvedDark": "#4d0b0a"
  },
  {
    "cssVar": "--sds-color-background-danger-tertiary",
    "collection": "color",
    "path": [
      "background",
      "danger",
      "tertiary"
    ],
    "type": "color",
    "description": "Bg/Danger/Tertiary",
    "light": "var(--sds-color-red-100)",
    "dark": "var(--sds-color-red-900)",
    "resolvedLight": "#fee9e7",
    "resolvedDark": "#4d0b0a"
  },
  {
    "cssVar": "--sds-color-background-danger-tertiary-hover",
    "collection": "color",
    "path": [
      "background",
      "danger",
      "tertiary-hover"
    ],
    "type": "color",
    "description": "Bg/Danger/Tertiary Hover",
    "light": "var(--sds-color-red-200)",
    "dark": "var(--sds-color-red-1000)",
    "resolvedLight": "#fdd3d0",
    "resolvedDark": "#300603"
  },
  {
    "cssVar": "--sds-color-background-disabled-default",
    "collection": "color",
    "path": [
      "background",
      "disabled",
      "default"
    ],
    "type": "color",
    "description": "Bg/Disabled/Default",
    "light": "var(--sds-color-brand-300)",
    "dark": "var(--sds-color-brand-700)",
    "resolvedLight": "#d9d9d9",
    "resolvedDark": "#383838"
  },
  {
    "cssVar": "--sds-color-background-utilities-scrim",
    "collection": "color",
    "path": [
      "background",
      "utilities",
      "scrim"
    ],
    "type": "color",
    "description": "Bg/Utilities/Scrim",
    "light": "#ffffffcc",
    "dark": "#000000cc",
    "resolvedLight": "#ffffffcc",
    "resolvedDark": "#000000cc"
  },
  {
    "cssVar": "--sds-color-background-utilities-blanket",
    "collection": "color",
    "path": [
      "background",
      "utilities",
      "blanket"
    ],
    "type": "color",
    "description": "Bg/Utilities/Blanket",
    "light": "#000000b2",
    "dark": "#000000b2",
    "resolvedLight": "#000000b2",
    "resolvedDark": "#000000b2"
  },
  {
    "cssVar": "--sds-color-background-utilities-overlay",
    "collection": "color",
    "path": [
      "background",
      "utilities",
      "overlay"
    ],
    "type": "color",
    "description": "Bg/Utilities/Overlay",
    "light": "#00000080",
    "dark": "#00000080",
    "resolvedLight": "#00000080",
    "resolvedDark": "#00000080"
  },
  {
    "cssVar": "--sds-color-background-utilities-measurement",
    "collection": "color",
    "path": [
      "background",
      "utilities",
      "measurement"
    ],
    "type": "color",
    "description": "Bg/Utilities/Measurement",
    "light": "var(--sds-color-pink-200)",
    "dark": "var(--sds-color-pink-800)",
    "resolvedLight": "#fae1fa",
    "resolvedDark": "#8a226f"
  },
  {
    "cssVar": "--sds-color-text-default-default",
    "collection": "color",
    "path": [
      "text",
      "default",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-gray-900)",
    "dark": "var(--sds-color-white-1000)",
    "resolvedLight": "#1e1e1e",
    "resolvedDark": "#ffffff"
  },
  {
    "cssVar": "--sds-color-text-default-secondary",
    "collection": "color",
    "path": [
      "text",
      "default",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-gray-500)",
    "dark": "var(--sds-color-white-500)",
    "resolvedLight": "#757575",
    "resolvedDark": "#ffffffb2"
  },
  {
    "cssVar": "--sds-color-text-default-tertiary",
    "collection": "color",
    "path": [
      "text",
      "default",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-gray-400)",
    "dark": "var(--sds-color-white-400)",
    "resolvedLight": "#b3b3b3",
    "resolvedDark": "#ffffff66"
  },
  {
    "cssVar": "--sds-color-text-neutral-default",
    "collection": "color",
    "path": [
      "text",
      "neutral",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-900)",
    "dark": "var(--sds-color-slate-200)",
    "resolvedLight": "#303030",
    "resolvedDark": "#e3e3e3"
  },
  {
    "cssVar": "--sds-color-text-neutral-secondary",
    "collection": "color",
    "path": [
      "text",
      "neutral",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-700)",
    "dark": "var(--sds-color-slate-300)",
    "resolvedLight": "#5a5a5a",
    "resolvedDark": "#cdcdcd"
  },
  {
    "cssVar": "--sds-color-text-neutral-tertiary",
    "collection": "color",
    "path": [
      "text",
      "neutral",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-600)",
    "dark": "var(--sds-color-slate-400)",
    "resolvedLight": "#767676",
    "resolvedDark": "#b2b2b2"
  },
  {
    "cssVar": "--sds-color-text-neutral-on-neutral",
    "collection": "color",
    "path": [
      "text",
      "neutral",
      "on-neutral"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-100)",
    "dark": "var(--sds-color-slate-1000)",
    "resolvedLight": "#f3f3f3",
    "resolvedDark": "#242424"
  },
  {
    "cssVar": "--sds-color-text-neutral-on-neutral-secondary",
    "collection": "color",
    "path": [
      "text",
      "neutral",
      "on-neutral-secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-900)",
    "dark": "var(--sds-color-slate-100)",
    "resolvedLight": "#303030",
    "resolvedDark": "#f3f3f3"
  },
  {
    "cssVar": "--sds-color-text-neutral-on-neutral-tertiary",
    "collection": "color",
    "path": [
      "text",
      "neutral",
      "on-neutral-tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-800)",
    "dark": "var(--sds-color-slate-100)",
    "resolvedLight": "#434343",
    "resolvedDark": "#f3f3f3"
  },
  {
    "cssVar": "--sds-color-text-brand-default",
    "collection": "color",
    "path": [
      "text",
      "brand",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-800)",
    "dark": "var(--sds-color-brand-100)",
    "resolvedLight": "#2c2c2c",
    "resolvedDark": "#f5f5f5"
  },
  {
    "cssVar": "--sds-color-text-brand-secondary",
    "collection": "color",
    "path": [
      "text",
      "brand",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-600)",
    "dark": "var(--sds-color-brand-300)",
    "resolvedLight": "#444444",
    "resolvedDark": "#d9d9d9"
  },
  {
    "cssVar": "--sds-color-text-brand-tertiary",
    "collection": "color",
    "path": [
      "text",
      "brand",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-500)",
    "dark": "var(--sds-color-brand-400)",
    "resolvedLight": "#757575",
    "resolvedDark": "#b3b3b3"
  },
  {
    "cssVar": "--sds-color-text-brand-on-brand",
    "collection": "color",
    "path": [
      "text",
      "brand",
      "on-brand"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-100)",
    "dark": "var(--sds-color-brand-900)",
    "resolvedLight": "#f5f5f5",
    "resolvedDark": "#1e1e1e"
  },
  {
    "cssVar": "--sds-color-text-brand-on-brand-secondary",
    "collection": "color",
    "path": [
      "text",
      "brand",
      "on-brand-secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-900)",
    "dark": "var(--sds-color-brand-100)",
    "resolvedLight": "#1e1e1e",
    "resolvedDark": "#f5f5f5"
  },
  {
    "cssVar": "--sds-color-text-brand-on-brand-tertiary",
    "collection": "color",
    "path": [
      "text",
      "brand",
      "on-brand-tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-800)",
    "dark": "var(--sds-color-brand-100)",
    "resolvedLight": "#2c2c2c",
    "resolvedDark": "#f5f5f5"
  },
  {
    "cssVar": "--sds-color-text-positive-default",
    "collection": "color",
    "path": [
      "text",
      "positive",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-green-800)",
    "dark": "var(--sds-color-green-200)",
    "resolvedLight": "#02542d",
    "resolvedDark": "#cff7d3"
  },
  {
    "cssVar": "--sds-color-text-positive-secondary",
    "collection": "color",
    "path": [
      "text",
      "positive",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-green-600)",
    "dark": "var(--sds-color-green-400)",
    "resolvedLight": "#009951",
    "resolvedDark": "#85e0a3"
  },
  {
    "cssVar": "--sds-color-text-positive-tertiary",
    "collection": "color",
    "path": [
      "text",
      "positive",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-green-500)",
    "dark": "var(--sds-color-green-600)",
    "resolvedLight": "#14ae5c",
    "resolvedDark": "#009951"
  },
  {
    "cssVar": "--sds-color-text-positive-on-positive",
    "collection": "color",
    "path": [
      "text",
      "positive",
      "on-positive"
    ],
    "type": "color",
    "light": "var(--sds-color-green-100)",
    "dark": "var(--sds-color-green-100)",
    "resolvedLight": "#ebffee",
    "resolvedDark": "#ebffee"
  },
  {
    "cssVar": "--sds-color-text-positive-on-positive-secondary",
    "collection": "color",
    "path": [
      "text",
      "positive",
      "on-positive-secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-green-800)",
    "dark": "var(--sds-color-green-100)",
    "resolvedLight": "#02542d",
    "resolvedDark": "#ebffee"
  },
  {
    "cssVar": "--sds-color-text-positive-on-positive-tertiary",
    "collection": "color",
    "path": [
      "text",
      "positive",
      "on-positive-tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-green-800)",
    "dark": "var(--sds-color-green-100)",
    "resolvedLight": "#02542d",
    "resolvedDark": "#ebffee"
  },
  {
    "cssVar": "--sds-color-text-warning-default",
    "collection": "color",
    "path": [
      "text",
      "warning",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-900)",
    "dark": "var(--sds-color-yellow-200)",
    "resolvedLight": "#522504",
    "resolvedDark": "#fff1c2"
  },
  {
    "cssVar": "--sds-color-text-warning-secondary",
    "collection": "color",
    "path": [
      "text",
      "warning",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-700)",
    "dark": "var(--sds-color-yellow-400)",
    "resolvedLight": "#975102",
    "resolvedDark": "#e8b931"
  },
  {
    "cssVar": "--sds-color-text-warning-tertiary",
    "collection": "color",
    "path": [
      "text",
      "warning",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-600)",
    "dark": "var(--sds-color-yellow-600)",
    "resolvedLight": "#bf6a02",
    "resolvedDark": "#bf6a02"
  },
  {
    "cssVar": "--sds-color-text-warning-on-warning",
    "collection": "color",
    "path": [
      "text",
      "warning",
      "on-warning"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-1000)",
    "dark": "var(--sds-color-yellow-1000)",
    "resolvedLight": "#401b01",
    "resolvedDark": "#401b01"
  },
  {
    "cssVar": "--sds-color-text-warning-on-warning-secondary",
    "collection": "color",
    "path": [
      "text",
      "warning",
      "on-warning-secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-800)",
    "dark": "var(--sds-color-yellow-100)",
    "resolvedLight": "#682d03",
    "resolvedDark": "#fffbeb"
  },
  {
    "cssVar": "--sds-color-text-warning-on-warning-tertiary",
    "collection": "color",
    "path": [
      "text",
      "warning",
      "on-warning-tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-900)",
    "dark": "var(--sds-color-yellow-100)",
    "resolvedLight": "#522504",
    "resolvedDark": "#fffbeb"
  },
  {
    "cssVar": "--sds-color-text-danger-default",
    "collection": "color",
    "path": [
      "text",
      "danger",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-red-700)",
    "dark": "var(--sds-color-red-200)",
    "resolvedLight": "#900b09",
    "resolvedDark": "#fdd3d0"
  },
  {
    "cssVar": "--sds-color-text-danger-secondary",
    "collection": "color",
    "path": [
      "text",
      "danger",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-red-600)",
    "dark": "var(--sds-color-red-400)",
    "resolvedLight": "#c00f0c",
    "resolvedDark": "#f4776a"
  },
  {
    "cssVar": "--sds-color-text-danger-tertiary",
    "collection": "color",
    "path": [
      "text",
      "danger",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-red-500)",
    "dark": "var(--sds-color-red-500)",
    "resolvedLight": "#ec221f",
    "resolvedDark": "#ec221f"
  },
  {
    "cssVar": "--sds-color-text-danger-on-danger",
    "collection": "color",
    "path": [
      "text",
      "danger",
      "on-danger"
    ],
    "type": "color",
    "light": "var(--sds-color-red-100)",
    "dark": "var(--sds-color-red-100)",
    "resolvedLight": "#fee9e7",
    "resolvedDark": "#fee9e7"
  },
  {
    "cssVar": "--sds-color-text-danger-on-danger-secondary",
    "collection": "color",
    "path": [
      "text",
      "danger",
      "on-danger-secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-red-700)",
    "dark": "var(--sds-color-red-100)",
    "resolvedLight": "#900b09",
    "resolvedDark": "#fee9e7"
  },
  {
    "cssVar": "--sds-color-text-danger-on-danger-tertiary",
    "collection": "color",
    "path": [
      "text",
      "danger",
      "on-danger-tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-red-700)",
    "dark": "var(--sds-color-red-100)",
    "resolvedLight": "#900b09",
    "resolvedDark": "#fee9e7"
  },
  {
    "cssVar": "--sds-color-text-disabled-default",
    "collection": "color",
    "path": [
      "text",
      "disabled",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-400)",
    "dark": "var(--sds-color-brand-500)",
    "resolvedLight": "#b3b3b3",
    "resolvedDark": "#757575"
  },
  {
    "cssVar": "--sds-color-text-disabled-on-disabled",
    "collection": "color",
    "path": [
      "text",
      "disabled",
      "on-disabled"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-400)",
    "dark": "var(--sds-color-brand-400)",
    "resolvedLight": "#b3b3b3",
    "resolvedDark": "#b3b3b3"
  },
  {
    "cssVar": "--sds-color-text-utilities-text-on-overlay",
    "collection": "color",
    "path": [
      "text",
      "utilities",
      "text-on-overlay"
    ],
    "type": "color",
    "light": "var(--sds-color-black-1000)",
    "dark": "var(--sds-color-white-1000)",
    "resolvedLight": "#0c0c0d",
    "resolvedDark": "#ffffff"
  },
  {
    "cssVar": "--sds-color-text-utilities-text-on-measurement",
    "collection": "color",
    "path": [
      "text",
      "utilities",
      "text-on-measurement"
    ],
    "type": "color",
    "light": "var(--sds-color-pink-800)",
    "dark": "var(--sds-color-pink-200)",
    "resolvedLight": "#8a226f",
    "resolvedDark": "#fae1fa"
  },
  {
    "cssVar": "--sds-color-border-default-default",
    "collection": "color",
    "path": [
      "border",
      "default",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-gray-300)",
    "dark": "var(--sds-color-gray-600)",
    "resolvedLight": "#d9d9d9",
    "resolvedDark": "#444444"
  },
  {
    "cssVar": "--sds-color-border-default-secondary",
    "collection": "color",
    "path": [
      "border",
      "default",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-gray-500)",
    "dark": "var(--sds-color-gray-500)",
    "resolvedLight": "#757575",
    "resolvedDark": "#757575"
  },
  {
    "cssVar": "--sds-color-border-default-tertiary",
    "collection": "color",
    "path": [
      "border",
      "default",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-gray-700)",
    "dark": "var(--sds-color-gray-400)",
    "resolvedLight": "#383838",
    "resolvedDark": "#b3b3b3"
  },
  {
    "cssVar": "--sds-color-border-neutral-default",
    "collection": "color",
    "path": [
      "border",
      "neutral",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-900)",
    "dark": "var(--sds-color-slate-100)",
    "resolvedLight": "#303030",
    "resolvedDark": "#f3f3f3"
  },
  {
    "cssVar": "--sds-color-border-neutral-secondary",
    "collection": "color",
    "path": [
      "border",
      "neutral",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-600)",
    "dark": "var(--sds-color-slate-500)",
    "resolvedLight": "#767676",
    "resolvedDark": "#949494"
  },
  {
    "cssVar": "--sds-color-border-neutral-tertiary",
    "collection": "color",
    "path": [
      "border",
      "neutral",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-400)",
    "dark": "var(--sds-color-slate-600)",
    "resolvedLight": "#b2b2b2",
    "resolvedDark": "#767676"
  },
  {
    "cssVar": "--sds-color-border-brand-default",
    "collection": "color",
    "path": [
      "border",
      "brand",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-800)",
    "dark": "var(--sds-color-brand-100)",
    "resolvedLight": "#2c2c2c",
    "resolvedDark": "#f5f5f5"
  },
  {
    "cssVar": "--sds-color-border-brand-secondary",
    "collection": "color",
    "path": [
      "border",
      "brand",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-600)",
    "dark": "var(--sds-color-brand-300)",
    "resolvedLight": "#444444",
    "resolvedDark": "#d9d9d9"
  },
  {
    "cssVar": "--sds-color-border-brand-tertiary",
    "collection": "color",
    "path": [
      "border",
      "brand",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-500)",
    "dark": "var(--sds-color-brand-400)",
    "resolvedLight": "#757575",
    "resolvedDark": "#b3b3b3"
  },
  {
    "cssVar": "--sds-color-border-positive-default",
    "collection": "color",
    "path": [
      "border",
      "positive",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-green-800)",
    "dark": "var(--sds-color-green-200)",
    "resolvedLight": "#02542d",
    "resolvedDark": "#cff7d3"
  },
  {
    "cssVar": "--sds-color-border-positive-secondary",
    "collection": "color",
    "path": [
      "border",
      "positive",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-green-600)",
    "dark": "var(--sds-color-green-400)",
    "resolvedLight": "#009951",
    "resolvedDark": "#85e0a3"
  },
  {
    "cssVar": "--sds-color-border-positive-tertiary",
    "collection": "color",
    "path": [
      "border",
      "positive",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-green-500)",
    "dark": "var(--sds-color-green-600)",
    "resolvedLight": "#14ae5c",
    "resolvedDark": "#009951"
  },
  {
    "cssVar": "--sds-color-border-warning-default",
    "collection": "color",
    "path": [
      "border",
      "warning",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-900)",
    "dark": "var(--sds-color-yellow-200)",
    "resolvedLight": "#522504",
    "resolvedDark": "#fff1c2"
  },
  {
    "cssVar": "--sds-color-border-warning-secondary",
    "collection": "color",
    "path": [
      "border",
      "warning",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-700)",
    "dark": "var(--sds-color-yellow-400)",
    "resolvedLight": "#975102",
    "resolvedDark": "#e8b931"
  },
  {
    "cssVar": "--sds-color-border-warning-tertiary",
    "collection": "color",
    "path": [
      "border",
      "warning",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-600)",
    "dark": "var(--sds-color-yellow-600)",
    "resolvedLight": "#bf6a02",
    "resolvedDark": "#bf6a02"
  },
  {
    "cssVar": "--sds-color-border-danger-default",
    "collection": "color",
    "path": [
      "border",
      "danger",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-red-700)",
    "dark": "var(--sds-color-red-200)",
    "resolvedLight": "#900b09",
    "resolvedDark": "#fdd3d0"
  },
  {
    "cssVar": "--sds-color-border-danger-secondary",
    "collection": "color",
    "path": [
      "border",
      "danger",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-red-600)",
    "dark": "var(--sds-color-red-400)",
    "resolvedLight": "#c00f0c",
    "resolvedDark": "#f4776a"
  },
  {
    "cssVar": "--sds-color-border-danger-tertiary",
    "collection": "color",
    "path": [
      "border",
      "danger",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-red-500)",
    "dark": "var(--sds-color-red-500)",
    "resolvedLight": "#ec221f",
    "resolvedDark": "#ec221f"
  },
  {
    "cssVar": "--sds-color-border-disabled-default",
    "collection": "color",
    "path": [
      "border",
      "disabled",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-400)",
    "dark": "var(--sds-color-brand-600)",
    "resolvedLight": "#b3b3b3",
    "resolvedDark": "#444444"
  },
  {
    "cssVar": "--sds-color-border-utilities-measurement",
    "collection": "color",
    "path": [
      "border",
      "utilities",
      "measurement"
    ],
    "type": "color",
    "light": "var(--sds-color-pink-400)",
    "dark": "var(--sds-color-pink-600)",
    "resolvedLight": "#f19edc",
    "resolvedDark": "#d732a8"
  },
  {
    "cssVar": "--sds-color-border-utilities-swatch",
    "collection": "color",
    "path": [
      "border",
      "utilities",
      "swatch"
    ],
    "type": "color",
    "light": "#0000003d",
    "dark": "#ffffff3d",
    "resolvedLight": "#0000003d",
    "resolvedDark": "#ffffff3d"
  },
  {
    "cssVar": "--sds-color-icon-default-default",
    "collection": "color",
    "path": [
      "icon",
      "default",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-gray-900)",
    "dark": "var(--sds-color-white-1000)",
    "resolvedLight": "#1e1e1e",
    "resolvedDark": "#ffffff"
  },
  {
    "cssVar": "--sds-color-icon-default-secondary",
    "collection": "color",
    "path": [
      "icon",
      "default",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-gray-500)",
    "dark": "var(--sds-color-white-500)",
    "resolvedLight": "#757575",
    "resolvedDark": "#ffffffb2"
  },
  {
    "cssVar": "--sds-color-icon-default-tertiary",
    "collection": "color",
    "path": [
      "icon",
      "default",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-gray-400)",
    "dark": "var(--sds-color-white-400)",
    "resolvedLight": "#b3b3b3",
    "resolvedDark": "#ffffff66"
  },
  {
    "cssVar": "--sds-color-icon-neutral-default",
    "collection": "color",
    "path": [
      "icon",
      "neutral",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-900)",
    "dark": "var(--sds-color-slate-200)",
    "resolvedLight": "#303030",
    "resolvedDark": "#e3e3e3"
  },
  {
    "cssVar": "--sds-color-icon-neutral-secondary",
    "collection": "color",
    "path": [
      "icon",
      "neutral",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-700)",
    "dark": "var(--sds-color-slate-300)",
    "resolvedLight": "#5a5a5a",
    "resolvedDark": "#cdcdcd"
  },
  {
    "cssVar": "--sds-color-icon-neutral-tertiary",
    "collection": "color",
    "path": [
      "icon",
      "neutral",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-600)",
    "dark": "var(--sds-color-slate-400)",
    "resolvedLight": "#767676",
    "resolvedDark": "#b2b2b2"
  },
  {
    "cssVar": "--sds-color-icon-neutral-on-neutral",
    "collection": "color",
    "path": [
      "icon",
      "neutral",
      "on-neutral"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-100)",
    "dark": "var(--sds-color-slate-1000)",
    "resolvedLight": "#f3f3f3",
    "resolvedDark": "#242424"
  },
  {
    "cssVar": "--sds-color-icon-neutral-on-neutral-secondary",
    "collection": "color",
    "path": [
      "icon",
      "neutral",
      "on-neutral-secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-900)",
    "dark": "var(--sds-color-slate-100)",
    "resolvedLight": "#303030",
    "resolvedDark": "#f3f3f3"
  },
  {
    "cssVar": "--sds-color-icon-neutral-on-neutral-tertiary",
    "collection": "color",
    "path": [
      "icon",
      "neutral",
      "on-neutral-tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-slate-800)",
    "dark": "var(--sds-color-slate-100)",
    "resolvedLight": "#434343",
    "resolvedDark": "#f3f3f3"
  },
  {
    "cssVar": "--sds-color-icon-brand-default",
    "collection": "color",
    "path": [
      "icon",
      "brand",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-800)",
    "dark": "var(--sds-color-brand-100)",
    "resolvedLight": "#2c2c2c",
    "resolvedDark": "#f5f5f5"
  },
  {
    "cssVar": "--sds-color-icon-brand-secondary",
    "collection": "color",
    "path": [
      "icon",
      "brand",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-600)",
    "dark": "var(--sds-color-brand-300)",
    "resolvedLight": "#444444",
    "resolvedDark": "#d9d9d9"
  },
  {
    "cssVar": "--sds-color-icon-brand-tertiary",
    "collection": "color",
    "path": [
      "icon",
      "brand",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-500)",
    "dark": "var(--sds-color-brand-400)",
    "resolvedLight": "#757575",
    "resolvedDark": "#b3b3b3"
  },
  {
    "cssVar": "--sds-color-icon-brand-on-brand",
    "collection": "color",
    "path": [
      "icon",
      "brand",
      "on-brand"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-100)",
    "dark": "var(--sds-color-brand-900)",
    "resolvedLight": "#f5f5f5",
    "resolvedDark": "#1e1e1e"
  },
  {
    "cssVar": "--sds-color-icon-brand-on-brand-secondary",
    "collection": "color",
    "path": [
      "icon",
      "brand",
      "on-brand-secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-900)",
    "dark": "var(--sds-color-brand-100)",
    "resolvedLight": "#1e1e1e",
    "resolvedDark": "#f5f5f5"
  },
  {
    "cssVar": "--sds-color-icon-brand-on-brand-tertiary",
    "collection": "color",
    "path": [
      "icon",
      "brand",
      "on-brand-tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-800)",
    "dark": "var(--sds-color-brand-100)",
    "resolvedLight": "#2c2c2c",
    "resolvedDark": "#f5f5f5"
  },
  {
    "cssVar": "--sds-color-icon-positive-default",
    "collection": "color",
    "path": [
      "icon",
      "positive",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-green-800)",
    "dark": "var(--sds-color-green-200)",
    "resolvedLight": "#02542d",
    "resolvedDark": "#cff7d3"
  },
  {
    "cssVar": "--sds-color-icon-positive-secondary",
    "collection": "color",
    "path": [
      "icon",
      "positive",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-green-600)",
    "dark": "var(--sds-color-green-400)",
    "resolvedLight": "#009951",
    "resolvedDark": "#85e0a3"
  },
  {
    "cssVar": "--sds-color-icon-positive-tertiary",
    "collection": "color",
    "path": [
      "icon",
      "positive",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-green-500)",
    "dark": "var(--sds-color-green-600)",
    "resolvedLight": "#14ae5c",
    "resolvedDark": "#009951"
  },
  {
    "cssVar": "--sds-color-icon-positive-on-positive",
    "collection": "color",
    "path": [
      "icon",
      "positive",
      "on-positive"
    ],
    "type": "color",
    "light": "var(--sds-color-green-100)",
    "dark": "var(--sds-color-green-100)",
    "resolvedLight": "#ebffee",
    "resolvedDark": "#ebffee"
  },
  {
    "cssVar": "--sds-color-icon-positive-on-positive-secondary",
    "collection": "color",
    "path": [
      "icon",
      "positive",
      "on-positive-secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-green-800)",
    "dark": "var(--sds-color-green-100)",
    "resolvedLight": "#02542d",
    "resolvedDark": "#ebffee"
  },
  {
    "cssVar": "--sds-color-icon-positive-on-positive-tertiary",
    "collection": "color",
    "path": [
      "icon",
      "positive",
      "on-positive-tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-green-900)",
    "dark": "var(--sds-color-green-100)",
    "resolvedLight": "#024023",
    "resolvedDark": "#ebffee"
  },
  {
    "cssVar": "--sds-color-icon-warning-default",
    "collection": "color",
    "path": [
      "icon",
      "warning",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-900)",
    "dark": "var(--sds-color-yellow-200)",
    "resolvedLight": "#522504",
    "resolvedDark": "#fff1c2"
  },
  {
    "cssVar": "--sds-color-icon-warning-secondary",
    "collection": "color",
    "path": [
      "icon",
      "warning",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-700)",
    "dark": "var(--sds-color-yellow-400)",
    "resolvedLight": "#975102",
    "resolvedDark": "#e8b931"
  },
  {
    "cssVar": "--sds-color-icon-warning-tertiary",
    "collection": "color",
    "path": [
      "icon",
      "warning",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-600)",
    "dark": "var(--sds-color-yellow-600)",
    "resolvedLight": "#bf6a02",
    "resolvedDark": "#bf6a02"
  },
  {
    "cssVar": "--sds-color-icon-warning-on-warning",
    "collection": "color",
    "path": [
      "icon",
      "warning",
      "on-warning"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-1000)",
    "dark": "var(--sds-color-yellow-1000)",
    "resolvedLight": "#401b01",
    "resolvedDark": "#401b01"
  },
  {
    "cssVar": "--sds-color-icon-warning-on-warning-secondary",
    "collection": "color",
    "path": [
      "icon",
      "warning",
      "on-warning-secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-800)",
    "dark": "var(--sds-color-yellow-100)",
    "resolvedLight": "#682d03",
    "resolvedDark": "#fffbeb"
  },
  {
    "cssVar": "--sds-color-icon-warning-on-warning-tertiary",
    "collection": "color",
    "path": [
      "icon",
      "warning",
      "on-warning-tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-yellow-900)",
    "dark": "var(--sds-color-yellow-100)",
    "resolvedLight": "#522504",
    "resolvedDark": "#fffbeb"
  },
  {
    "cssVar": "--sds-color-icon-danger-default",
    "collection": "color",
    "path": [
      "icon",
      "danger",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-red-700)",
    "dark": "var(--sds-color-red-200)",
    "resolvedLight": "#900b09",
    "resolvedDark": "#fdd3d0"
  },
  {
    "cssVar": "--sds-color-icon-danger-secondary",
    "collection": "color",
    "path": [
      "icon",
      "danger",
      "secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-red-600)",
    "dark": "var(--sds-color-red-400)",
    "resolvedLight": "#c00f0c",
    "resolvedDark": "#f4776a"
  },
  {
    "cssVar": "--sds-color-icon-danger-tertiary",
    "collection": "color",
    "path": [
      "icon",
      "danger",
      "tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-red-500)",
    "dark": "var(--sds-color-red-500)",
    "resolvedLight": "#ec221f",
    "resolvedDark": "#ec221f"
  },
  {
    "cssVar": "--sds-color-icon-danger-on-danger",
    "collection": "color",
    "path": [
      "icon",
      "danger",
      "on-danger"
    ],
    "type": "color",
    "light": "var(--sds-color-red-100)",
    "dark": "var(--sds-color-red-100)",
    "resolvedLight": "#fee9e7",
    "resolvedDark": "#fee9e7"
  },
  {
    "cssVar": "--sds-color-icon-danger-on-danger-secondary",
    "collection": "color",
    "path": [
      "icon",
      "danger",
      "on-danger-secondary"
    ],
    "type": "color",
    "light": "var(--sds-color-red-700)",
    "dark": "var(--sds-color-red-100)",
    "resolvedLight": "#900b09",
    "resolvedDark": "#fee9e7"
  },
  {
    "cssVar": "--sds-color-icon-danger-on-danger-tertiary",
    "collection": "color",
    "path": [
      "icon",
      "danger",
      "on-danger-tertiary"
    ],
    "type": "color",
    "light": "var(--sds-color-red-700)",
    "dark": "var(--sds-color-red-100)",
    "resolvedLight": "#900b09",
    "resolvedDark": "#fee9e7"
  },
  {
    "cssVar": "--sds-color-icon-disabled-default",
    "collection": "color",
    "path": [
      "icon",
      "disabled",
      "default"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-400)",
    "dark": "var(--sds-color-brand-500)",
    "resolvedLight": "#b3b3b3",
    "resolvedDark": "#757575"
  },
  {
    "cssVar": "--sds-color-icon-disabled-on-disabled",
    "collection": "color",
    "path": [
      "icon",
      "disabled",
      "on-disabled"
    ],
    "type": "color",
    "light": "var(--sds-color-brand-400)",
    "dark": "var(--sds-color-brand-400)",
    "resolvedLight": "#b3b3b3",
    "resolvedDark": "#b3b3b3"
  },
  {
    "cssVar": "--sds-color-icon-utilities-icon",
    "collection": "color",
    "path": [
      "icon",
      "utilities",
      "icon"
    ],
    "type": "color",
    "light": "var(--sds-color-pink-600)",
    "dark": "var(--sds-color-pink-400)",
    "resolvedLight": "#d732a8",
    "resolvedDark": "#f19edc"
  },
  {
    "cssVar": "--sds-color-icon-utilities-icon-on-measurement",
    "collection": "color",
    "path": [
      "icon",
      "utilities",
      "icon-on-measurement"
    ],
    "type": "color",
    "light": "var(--sds-color-pink-800)",
    "dark": "var(--sds-color-pink-200)",
    "resolvedLight": "#8a226f",
    "resolvedDark": "#fae1fa"
  },
  {
    "cssVar": "--sds-size-space-0",
    "collection": "size",
    "path": [
      "space",
      "0"
    ],
    "type": "number",
    "light": "0rem",
    "resolvedLight": "0"
  },
  {
    "cssVar": "--sds-size-space-100",
    "collection": "size",
    "path": [
      "space",
      "100"
    ],
    "type": "number",
    "light": "0.25rem",
    "resolvedLight": "4"
  },
  {
    "cssVar": "--sds-size-space-150",
    "collection": "size",
    "path": [
      "space",
      "150"
    ],
    "type": "number",
    "light": "0.375rem",
    "resolvedLight": "6"
  },
  {
    "cssVar": "--sds-size-space-200",
    "collection": "size",
    "path": [
      "space",
      "200"
    ],
    "type": "number",
    "light": "0.5rem",
    "resolvedLight": "8"
  },
  {
    "cssVar": "--sds-size-space-300",
    "collection": "size",
    "path": [
      "space",
      "300"
    ],
    "type": "number",
    "light": "0.75rem",
    "resolvedLight": "12"
  },
  {
    "cssVar": "--sds-size-space-400",
    "collection": "size",
    "path": [
      "space",
      "400"
    ],
    "type": "number",
    "light": "1rem",
    "resolvedLight": "16"
  },
  {
    "cssVar": "--sds-size-space-600",
    "collection": "size",
    "path": [
      "space",
      "600"
    ],
    "type": "number",
    "light": "1.5rem",
    "resolvedLight": "24"
  },
  {
    "cssVar": "--sds-size-space-800",
    "collection": "size",
    "path": [
      "space",
      "800"
    ],
    "type": "number",
    "light": "2rem",
    "resolvedLight": "32"
  },
  {
    "cssVar": "--sds-size-space-1200",
    "collection": "size",
    "path": [
      "space",
      "1200"
    ],
    "type": "number",
    "light": "3rem",
    "resolvedLight": "48"
  },
  {
    "cssVar": "--sds-size-space-1600",
    "collection": "size",
    "path": [
      "space",
      "1600"
    ],
    "type": "number",
    "light": "4rem",
    "resolvedLight": "64"
  },
  {
    "cssVar": "--sds-size-space-2400",
    "collection": "size",
    "path": [
      "space",
      "2400"
    ],
    "type": "number",
    "light": "6rem",
    "resolvedLight": "96"
  },
  {
    "cssVar": "--sds-size-space-4000",
    "collection": "size",
    "path": [
      "space",
      "4000"
    ],
    "type": "number",
    "light": "10rem",
    "resolvedLight": "160"
  },
  {
    "cssVar": "--sds-size-space-050",
    "collection": "size",
    "path": [
      "space",
      "050"
    ],
    "type": "number",
    "light": "0.125rem",
    "resolvedLight": "2"
  },
  {
    "cssVar": "--sds-size-space-negative-100",
    "collection": "size",
    "path": [
      "space",
      "negative-100"
    ],
    "type": "number",
    "light": "-0.25rem",
    "resolvedLight": "-4"
  },
  {
    "cssVar": "--sds-size-space-negative-200",
    "collection": "size",
    "path": [
      "space",
      "negative-200"
    ],
    "type": "number",
    "light": "-0.5rem",
    "resolvedLight": "-8"
  },
  {
    "cssVar": "--sds-size-space-negative-300",
    "collection": "size",
    "path": [
      "space",
      "negative-300"
    ],
    "type": "number",
    "light": "-0.75rem",
    "resolvedLight": "-12"
  },
  {
    "cssVar": "--sds-size-space-negative-400",
    "collection": "size",
    "path": [
      "space",
      "negative-400"
    ],
    "type": "number",
    "light": "-1rem",
    "resolvedLight": "-16"
  },
  {
    "cssVar": "--sds-size-space-negative-600",
    "collection": "size",
    "path": [
      "space",
      "negative-600"
    ],
    "type": "number",
    "light": "-1.5rem",
    "resolvedLight": "-24"
  },
  {
    "cssVar": "--sds-size-radius-100",
    "collection": "size",
    "path": [
      "radius",
      "100"
    ],
    "type": "number",
    "light": "0.25rem",
    "resolvedLight": "4"
  },
  {
    "cssVar": "--sds-size-radius-200",
    "collection": "size",
    "path": [
      "radius",
      "200"
    ],
    "type": "number",
    "light": "0.5rem",
    "resolvedLight": "8"
  },
  {
    "cssVar": "--sds-size-radius-400",
    "collection": "size",
    "path": [
      "radius",
      "400"
    ],
    "type": "number",
    "light": "1rem",
    "resolvedLight": "16"
  },
  {
    "cssVar": "--sds-size-radius-full",
    "collection": "size",
    "path": [
      "radius",
      "full"
    ],
    "type": "number",
    "light": "624.9375rem",
    "resolvedLight": "9999"
  },
  {
    "cssVar": "--sds-size-blur-100",
    "collection": "size",
    "path": [
      "blur",
      "100"
    ],
    "type": "number",
    "light": "0.25rem",
    "resolvedLight": "4"
  },
  {
    "cssVar": "--sds-size-depth-0",
    "collection": "size",
    "path": [
      "depth",
      "0"
    ],
    "type": "number",
    "light": "0rem",
    "resolvedLight": "0"
  },
  {
    "cssVar": "--sds-size-depth-100",
    "collection": "size",
    "path": [
      "depth",
      "100"
    ],
    "type": "number",
    "light": "0.25rem",
    "resolvedLight": "4"
  },
  {
    "cssVar": "--sds-size-depth-200",
    "collection": "size",
    "path": [
      "depth",
      "200"
    ],
    "type": "number",
    "light": "0.5rem",
    "resolvedLight": "8"
  },
  {
    "cssVar": "--sds-size-depth-400",
    "collection": "size",
    "path": [
      "depth",
      "400"
    ],
    "type": "number",
    "light": "1rem",
    "resolvedLight": "16"
  },
  {
    "cssVar": "--sds-size-depth-800",
    "collection": "size",
    "path": [
      "depth",
      "800"
    ],
    "type": "number",
    "light": "2rem",
    "resolvedLight": "32"
  },
  {
    "cssVar": "--sds-size-depth-1200",
    "collection": "size",
    "path": [
      "depth",
      "1200"
    ],
    "type": "number",
    "light": "3rem",
    "resolvedLight": "48"
  },
  {
    "cssVar": "--sds-size-depth-025",
    "collection": "size",
    "path": [
      "depth",
      "025"
    ],
    "type": "number",
    "light": "0.0625rem",
    "resolvedLight": "1"
  },
  {
    "cssVar": "--sds-size-depth-negative-025",
    "collection": "size",
    "path": [
      "depth",
      "negative-025"
    ],
    "type": "number",
    "light": "-0.0625rem",
    "resolvedLight": "-1"
  },
  {
    "cssVar": "--sds-size-depth-negative-100",
    "collection": "size",
    "path": [
      "depth",
      "negative-100"
    ],
    "type": "number",
    "light": "-0.25rem",
    "resolvedLight": "-4"
  },
  {
    "cssVar": "--sds-size-depth-negative-200",
    "collection": "size",
    "path": [
      "depth",
      "negative-200"
    ],
    "type": "number",
    "light": "-0.5rem",
    "resolvedLight": "-8"
  },
  {
    "cssVar": "--sds-size-depth-negative-400",
    "collection": "size",
    "path": [
      "depth",
      "negative-400"
    ],
    "type": "number",
    "light": "-1rem",
    "resolvedLight": "-16"
  },
  {
    "cssVar": "--sds-size-depth-negative-800",
    "collection": "size",
    "path": [
      "depth",
      "negative-800"
    ],
    "type": "number",
    "light": "-2rem",
    "resolvedLight": "-32"
  },
  {
    "cssVar": "--sds-size-depth-negative-1200",
    "collection": "size",
    "path": [
      "depth",
      "negative-1200"
    ],
    "type": "number",
    "light": "-3rem",
    "resolvedLight": "-48"
  },
  {
    "cssVar": "--sds-size-stroke-border",
    "collection": "size",
    "path": [
      "stroke",
      "border"
    ],
    "type": "number",
    "light": "0.0625rem",
    "resolvedLight": "1"
  },
  {
    "cssVar": "--sds-size-stroke-focus-ring",
    "collection": "size",
    "path": [
      "stroke",
      "focus-ring"
    ],
    "type": "number",
    "light": "0.125rem",
    "resolvedLight": "2"
  },
  {
    "cssVar": "--sds-size-icon-small",
    "collection": "size",
    "path": [
      "icon",
      "small"
    ],
    "type": "number",
    "light": "1.5rem",
    "resolvedLight": "24"
  },
  {
    "cssVar": "--sds-size-icon-medium",
    "collection": "size",
    "path": [
      "icon",
      "medium"
    ],
    "type": "number",
    "light": "2rem",
    "resolvedLight": "32"
  },
  {
    "cssVar": "--sds-size-icon-large",
    "collection": "size",
    "path": [
      "icon",
      "large"
    ],
    "type": "number",
    "light": "2.5rem",
    "resolvedLight": "40"
  },
  {
    "cssVar": "--sds-typography-family-sans",
    "collection": "typography_primitives",
    "path": [
      "family-sans"
    ],
    "type": "fontFamily",
    "light": "\"Inter\", sans-serif",
    "resolvedLight": "Inter"
  },
  {
    "cssVar": "--sds-typography-family-serif",
    "collection": "typography_primitives",
    "path": [
      "family-serif"
    ],
    "type": "fontFamily",
    "light": "\"Noto Serif\", serif",
    "resolvedLight": "Noto Serif"
  },
  {
    "cssVar": "--sds-typography-family-mono",
    "collection": "typography_primitives",
    "path": [
      "family-mono"
    ],
    "type": "fontFamily",
    "light": "\"Roboto Mono\", monospace",
    "resolvedLight": "Roboto Mono"
  },
  {
    "cssVar": "--sds-typography-scale-01",
    "collection": "typography_primitives",
    "path": [
      "scale-01"
    ],
    "type": "number",
    "light": "0.75rem",
    "resolvedLight": "12"
  },
  {
    "cssVar": "--sds-typography-scale-02",
    "collection": "typography_primitives",
    "path": [
      "scale-02"
    ],
    "type": "number",
    "light": "0.875rem",
    "resolvedLight": "14"
  },
  {
    "cssVar": "--sds-typography-scale-03",
    "collection": "typography_primitives",
    "path": [
      "scale-03"
    ],
    "type": "number",
    "light": "1rem",
    "resolvedLight": "16"
  },
  {
    "cssVar": "--sds-typography-scale-04",
    "collection": "typography_primitives",
    "path": [
      "scale-04"
    ],
    "type": "number",
    "light": "1.25rem",
    "resolvedLight": "20"
  },
  {
    "cssVar": "--sds-typography-scale-05",
    "collection": "typography_primitives",
    "path": [
      "scale-05"
    ],
    "type": "number",
    "light": "1.5rem",
    "resolvedLight": "24"
  },
  {
    "cssVar": "--sds-typography-scale-06",
    "collection": "typography_primitives",
    "path": [
      "scale-06"
    ],
    "type": "number",
    "light": "2rem",
    "resolvedLight": "32"
  },
  {
    "cssVar": "--sds-typography-scale-07",
    "collection": "typography_primitives",
    "path": [
      "scale-07"
    ],
    "type": "number",
    "light": "2.5rem",
    "resolvedLight": "40"
  },
  {
    "cssVar": "--sds-typography-scale-08",
    "collection": "typography_primitives",
    "path": [
      "scale-08"
    ],
    "type": "number",
    "light": "3rem",
    "resolvedLight": "48"
  },
  {
    "cssVar": "--sds-typography-scale-09",
    "collection": "typography_primitives",
    "path": [
      "scale-09"
    ],
    "type": "number",
    "light": "4rem",
    "resolvedLight": "64"
  },
  {
    "cssVar": "--sds-typography-scale-10",
    "collection": "typography_primitives",
    "path": [
      "scale-10"
    ],
    "type": "number",
    "light": "4.5rem",
    "resolvedLight": "72"
  },
  {
    "cssVar": "--sds-typography-weight-thin",
    "collection": "typography_primitives",
    "path": [
      "weight-thin"
    ],
    "type": "fontWeight",
    "light": "100",
    "resolvedLight": "100"
  },
  {
    "cssVar": "--sds-typography-weight-extra-light",
    "collection": "typography_primitives",
    "path": [
      "weight-extra-light"
    ],
    "type": "fontWeight",
    "light": "200",
    "resolvedLight": "200"
  },
  {
    "cssVar": "--sds-typography-weight-light",
    "collection": "typography_primitives",
    "path": [
      "weight-light"
    ],
    "type": "fontWeight",
    "light": "300",
    "resolvedLight": "300"
  },
  {
    "cssVar": "--sds-typography-weight-regular",
    "collection": "typography_primitives",
    "path": [
      "weight-regular"
    ],
    "type": "fontWeight",
    "light": "400",
    "resolvedLight": "400"
  },
  {
    "cssVar": "--sds-typography-weight-medium",
    "collection": "typography_primitives",
    "path": [
      "weight-medium"
    ],
    "type": "fontWeight",
    "light": "500",
    "resolvedLight": "500"
  },
  {
    "cssVar": "--sds-typography-weight-semibold",
    "collection": "typography_primitives",
    "path": [
      "weight-semibold"
    ],
    "type": "fontWeight",
    "light": "600",
    "resolvedLight": "600"
  },
  {
    "cssVar": "--sds-typography-weight-bold",
    "collection": "typography_primitives",
    "path": [
      "weight-bold"
    ],
    "type": "fontWeight",
    "light": "700",
    "resolvedLight": "700"
  },
  {
    "cssVar": "--sds-typography-weight-extra-bold",
    "collection": "typography_primitives",
    "path": [
      "weight-extra-bold"
    ],
    "type": "fontWeight",
    "light": "800",
    "resolvedLight": "800"
  },
  {
    "cssVar": "--sds-typography-weight-black",
    "collection": "typography_primitives",
    "path": [
      "weight-black"
    ],
    "type": "fontWeight",
    "light": "900",
    "resolvedLight": "900"
  },
  {
    "cssVar": "--sds-typography-title-hero-font-family",
    "collection": "typography",
    "path": [
      "title-hero",
      "font-family"
    ],
    "type": "fontFamily",
    "light": "var(--sds-typography-family-sans)",
    "resolvedLight": "Inter"
  },
  {
    "cssVar": "--sds-typography-title-hero-size",
    "collection": "typography",
    "path": [
      "title-hero",
      "size"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-10)",
    "resolvedLight": "72"
  },
  {
    "cssVar": "--sds-typography-title-hero-font-weight",
    "collection": "typography",
    "path": [
      "title-hero",
      "font-weight"
    ],
    "type": "fontWeight",
    "light": "var(--sds-typography-weight-bold)",
    "resolvedLight": "700"
  },
  {
    "cssVar": "--sds-typography-title-page-font-family",
    "collection": "typography",
    "path": [
      "title-page",
      "font-family"
    ],
    "type": "fontFamily",
    "light": "var(--sds-typography-family-sans)",
    "resolvedLight": "Inter"
  },
  {
    "cssVar": "--sds-typography-title-page-size-small",
    "collection": "typography",
    "path": [
      "title-page",
      "size-small"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-07)",
    "resolvedLight": "40"
  },
  {
    "cssVar": "--sds-typography-title-page-size-base",
    "collection": "typography",
    "path": [
      "title-page",
      "size-base"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-08)",
    "resolvedLight": "48"
  },
  {
    "cssVar": "--sds-typography-title-page-size-large",
    "collection": "typography",
    "path": [
      "title-page",
      "size-large"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-09)",
    "resolvedLight": "64"
  },
  {
    "cssVar": "--sds-typography-title-page-font-weight",
    "collection": "typography",
    "path": [
      "title-page",
      "font-weight"
    ],
    "type": "fontWeight",
    "light": "var(--sds-typography-weight-bold)",
    "resolvedLight": "700"
  },
  {
    "cssVar": "--sds-typography-subtitle-font-family",
    "collection": "typography",
    "path": [
      "subtitle",
      "font-family"
    ],
    "type": "fontFamily",
    "light": "var(--sds-typography-family-sans)",
    "resolvedLight": "Inter"
  },
  {
    "cssVar": "--sds-typography-subtitle-size-small",
    "collection": "typography",
    "path": [
      "subtitle",
      "size-small"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-05)",
    "resolvedLight": "24"
  },
  {
    "cssVar": "--sds-typography-subtitle-size-base",
    "collection": "typography",
    "path": [
      "subtitle",
      "size-base"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-06)",
    "resolvedLight": "32"
  },
  {
    "cssVar": "--sds-typography-subtitle-size-large",
    "collection": "typography",
    "path": [
      "subtitle",
      "size-large"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-07)",
    "resolvedLight": "40"
  },
  {
    "cssVar": "--sds-typography-subtitle-font-weight",
    "collection": "typography",
    "path": [
      "subtitle",
      "font-weight"
    ],
    "type": "fontWeight",
    "light": "var(--sds-typography-weight-regular)",
    "resolvedLight": "400"
  },
  {
    "cssVar": "--sds-typography-heading-font-family",
    "collection": "typography",
    "path": [
      "heading",
      "font-family"
    ],
    "type": "fontFamily",
    "light": "var(--sds-typography-family-sans)",
    "resolvedLight": "Inter"
  },
  {
    "cssVar": "--sds-typography-heading-size-small",
    "collection": "typography",
    "path": [
      "heading",
      "size-small"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-04)",
    "resolvedLight": "20"
  },
  {
    "cssVar": "--sds-typography-heading-size-base",
    "collection": "typography",
    "path": [
      "heading",
      "size-base"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-05)",
    "resolvedLight": "24"
  },
  {
    "cssVar": "--sds-typography-heading-size-large",
    "collection": "typography",
    "path": [
      "heading",
      "size-large"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-06)",
    "resolvedLight": "32"
  },
  {
    "cssVar": "--sds-typography-heading-font-weight",
    "collection": "typography",
    "path": [
      "heading",
      "font-weight"
    ],
    "type": "fontWeight",
    "light": "var(--sds-typography-weight-semibold)",
    "resolvedLight": "600"
  },
  {
    "cssVar": "--sds-typography-subheading-font-family",
    "collection": "typography",
    "path": [
      "subheading",
      "font-family"
    ],
    "type": "fontFamily",
    "light": "var(--sds-typography-family-sans)",
    "resolvedLight": "Inter"
  },
  {
    "cssVar": "--sds-typography-subheading-size-small",
    "collection": "typography",
    "path": [
      "subheading",
      "size-small"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-03)",
    "resolvedLight": "16"
  },
  {
    "cssVar": "--sds-typography-subheading-size-medium",
    "collection": "typography",
    "path": [
      "subheading",
      "size-medium"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-04)",
    "resolvedLight": "20"
  },
  {
    "cssVar": "--sds-typography-subheading-size-large",
    "collection": "typography",
    "path": [
      "subheading",
      "size-large"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-05)",
    "resolvedLight": "24"
  },
  {
    "cssVar": "--sds-typography-subheading-font-weight",
    "collection": "typography",
    "path": [
      "subheading",
      "font-weight"
    ],
    "type": "fontWeight",
    "light": "var(--sds-typography-weight-regular)",
    "resolvedLight": "400"
  },
  {
    "cssVar": "--sds-typography-body-font-family",
    "collection": "typography",
    "path": [
      "body",
      "font-family"
    ],
    "type": "fontFamily",
    "light": "var(--sds-typography-family-sans)",
    "resolvedLight": "Inter"
  },
  {
    "cssVar": "--sds-typography-body-size-small",
    "collection": "typography",
    "path": [
      "body",
      "size-small"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-02)",
    "resolvedLight": "14"
  },
  {
    "cssVar": "--sds-typography-body-size-medium",
    "collection": "typography",
    "path": [
      "body",
      "size-medium"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-03)",
    "resolvedLight": "16"
  },
  {
    "cssVar": "--sds-typography-body-size-large",
    "collection": "typography",
    "path": [
      "body",
      "size-large"
    ],
    "type": "number",
    "light": "var(--sds-typography-scale-04)",
    "resolvedLight": "20"
  },
  {
    "cssVar": "--sds-typography-body-font-weight-regular",
    "collection": "typography",
    "path": [
      "body",
      "font-weight-regular"
    ],
    "type": "fontWeight",
    "light": "var(--sds-typography-weight-regular)",
    "resolvedLight": "400"
  },
  {
    "cssVar": "--sds-typography-body-font-weight-strong",
    "collection": "typography",
    "path": [
      "body",
      "font-weight-strong"
    ],
    "type": "fontWeight",
    "light": "var(--sds-typography-weight-semibold)",
    "resolvedLight": "600"
  },
  {
    "cssVar": "--sds-typography-code-font-family",
    "collection": "typography",
    "path": [
      "code",
      "font-family"
    ],
    "type": "fontFamily",
    "light": "var(--sds-typography-family-mono)",
    "resolvedLight": "Roboto Mono"
  },
  {
    "cssVar": "--sds-typography-code-size-small",
    "collection": "typography",
    "path": [
      "code",
      "size-small"
    ],
    "type": "number",
    "light": "var(--sds-typography-body-size-small)",
    "resolvedLight": "14"
  },
  {
    "cssVar": "--sds-typography-code-size-base",
    "collection": "typography",
    "path": [
      "code",
      "size-base"
    ],
    "type": "number",
    "light": "var(--sds-typography-body-size-medium)",
    "resolvedLight": "16"
  },
  {
    "cssVar": "--sds-typography-code-size-large",
    "collection": "typography",
    "path": [
      "code",
      "size-large"
    ],
    "type": "number",
    "light": "var(--sds-typography-body-size-large)",
    "resolvedLight": "20"
  },
  {
    "cssVar": "--sds-typography-code-font-weight",
    "collection": "typography",
    "path": [
      "code",
      "font-weight"
    ],
    "type": "fontWeight",
    "light": "var(--sds-typography-body-font-weight-regular)",
    "resolvedLight": "400"
  }
]
